"""empty message

Revision ID: ea4e3cb41e9a
Revises: 8e6709b3629c
Create Date: 2021-09-04 15:56:22.843260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4e3cb41e9a'
down_revision = '8e6709b3629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('namecoin', sa.String(length=250), nullable=False),
    sa.Column('symbol', sa.String(length=250), nullable=False),
    sa.Column('market_cap_rank', sa.Integer(), nullable=False),
    sa.Column('coingecko_id', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coingecko_id'),
    sa.UniqueConstraint('market_cap_rank'),
    sa.UniqueConstraint('namecoin'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos_on_crypto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos_on_crypto')
    op.drop_table('articles')
    op.drop_table('coin')
    # ### end Alembic commands ###
